export const GET_RECIPE = 'GET_RECIPE';
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS';
export const FETCH_RECIPE_FAILURE = 'FETCH_RECIPE_FAILURE';
export const FETCH_RECIPES_REQUEST = 'FETCH_RECIPES_REQUEST';
