export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

export const CREATE_RECIPE = 'CREATE_RECIPE';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_FAILURE = 'CREATE_RECIPE_FAILURE';

export const UPLOAD_MEDIA = 'UPLOAD_MEDIA';
export const MEDIA_UPLOAD_SUCCESS = 'MEDIA_UPLOAD_SUCCESS';
export const MEDIA_UPLOAD_RESET = 'MEDIA_UPLOAD_RESET';

export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_FAILURE = 'SOCIAL_LOGIN_FAILURE';
export const SOCIAL_LOGIN_REQUEST = 'SOCIAL_LOGIN_REQUEST';

export const GET_RECIPE_REQUEST = 'GET_RECIPE_REQUEST';
export const GET_SINGLE_RECIPE_SUCCESS = 'GET_SINGLE_RECIPE_SUCCESS';
export const GET_SINGLE_RECIPE_FAILURE = 'GET_SINGLE_RECIPE_FAILURE';
